"""empty message

Revision ID: 775513414580
Revises: b61808c001b3
Create Date: 2024-10-24 00:10:13.732697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775513414580'
down_revision = 'b61808c001b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocked_list')
    # ### end Alembic commands ###
